spring:
  application:
    name: Events

activity-log:
  endpoint: http://localhost:8081/demo/api/v1/log

server:
  port: 8080

threadPool:
  corePoolSize: 10
  maxPoolSize: 20
  maxQueueSize: 200
  namePrefix: sub-system-call-thread

